export interface Product {
  id: string;
  name: string;
  sku: string;
  category: string;
  price: number;
  unit: string;
  stock: number;
  stockStatus: "in-stock" | "low-stock" | "out-of-stock";
  image: string;
  description: string;
  deliveryDays: number;
  brand: string;
  minOrder: number;
  isRecurring?: boolean;
  tags: string[];
  unitPrice?: number;
  unitPriceUnit?: string;
  isActive?: boolean;
}

export const categories = [
  { id: "oficina", name: "Útiles de Oficina", icon: "PenLine" },
  { id: "empaque", name: "Empaque y Embalaje", icon: "Package" },
  { id: "limpieza", name: "Limpieza e Higiene", icon: "Sparkles" },
  { id: "sabanillas", name: "Sabanillas", icon: "ClipboardList" },
  { id: "cafeteria", name: "Cafetería y Alimentos", icon: "Coffee" },
  { id: "seguridad", name: "Seguridad Industrial", icon: "Shield" },
  { id: "tecnologia", name: "Tecnología y Accesorios", icon: "Monitor" },
];

export const products: Product[] = [
  {
    id: "13",
    name: "Bolígrafo Faber-Castell Trilux 035 Rojo",
    sku: "TMO-OFI-001",
    category: "oficina",
    price: 29.00,
    unit: "caja",
    stock: 2000,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/Lapiceros/Boligrafo%20faber%20castell%20trilux%20035%20%20Rojo.png",
    description: "Bolígrafo Faber Trilux T/Sec (035) P/Fina 0.8 mm Rojo. 50 unidades por caja. Cuerpo triangular ergonómico color verde translúcido. Escritura suave y fluida, ideal para oficinas, almacenes y uso industrial.",
    deliveryDays: 1,
    brand: "Faber-Castell",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Bolígrafo", "Escritura", "Rojo"],
  },
  {
    id: "14",
    name: "Bolígrafo Faber-Castell Trilux 035 Azul",
    sku: "TMO-OFI-002",
    category: "oficina",
    price: 29.00,
    unit: "caja",
    stock: 3500,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/Lapiceros/Boligrafo%20faber%20castell%20trilux%20035%20azul.png",
    description: "Bolígrafo Faber Trilux T/Sec (035) P/Fina 0.8 mm Azul. 50 unidades por caja. Cuerpo triangular ergonómico color verde translúcido. Escritura suave y fluida, ideal para oficinas, almacenes y uso industrial.",
    deliveryDays: 1,
    brand: "Faber-Castell",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Bolígrafo", "Escritura", "Azul"],
  },
  {
    id: "15",
    name: "Bolígrafo Faber-Castell Trilux 035 Negro",
    sku: "TMO-OFI-003",
    category: "oficina",
    price: 29.00,
    unit: "caja",
    stock: 1800,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/Lapiceros/Boligrafo%20faber%20castell%20trilux%20035%20negro.png",
    description: "Bolígrafo Faber Trilux T/Sec (035) P/Fina 0.8 mm Negro. 50 unidades por caja. Cuerpo triangular ergonómico color verde translúcido. Escritura suave y fluida, ideal para oficinas, almacenes y uso industrial.",
    deliveryDays: 1,
    brand: "Faber-Castell",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Bolígrafo", "Escritura", "Negro"],
  },
  {
    id: "16",
    name: "Papel Fotocopia A4 75g Millennium",
    sku: "TMO-OFI-004",
    category: "oficina",
    price: 108.00,
    unit: "caja",
    stock: 500,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/hojas%20bond/Papel%20Fotocopia%20A4%2075%20G%20Milenium.png",
    description: "Papel Fotocopia A4 75g Millennium. Caja con 5 paquetes de 500 hojas. Precio por paquete: S/ 11.80. Blancura óptima para impresión láser e inyección de tinta. Ideal para oficinas, almacenes y uso diario.",
    deliveryDays: 1,
    brand: "Millennium",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Papel", "A4", "Impresión"],
    unitPrice: 11.80,
    unitPriceUnit: "pqte",
  },
  {
    id: "17",
    name: "Papel Fotocopia A4 75g Report",
    sku: "TMO-OFI-005",
    category: "oficina",
    price: 135.00,
    unit: "caja",
    stock: 350,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/hojas%20bond/Papel%20Fotocopia%20A4%2080%20G%c2%a0Report.png",
    description: "Papel Fotocopia A4 75g Report. Caja con 10 paquetes de 500 hojas. Precio por paquete: S/ 14.50. Alta blancura y rendimiento superior. Compatible con impresoras láser, inyección de tinta y fotocopiadoras.",
    deliveryDays: 1,
    brand: "Report",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Papel", "A4", "Impresión"],
    unitPrice: 14.50,
    unitPriceUnit: "pqte",
  },
  {
    id: "18",
    name: "Papel Fotocopia A4 80g Report",
    sku: "TMO-OFI-006",
    category: "oficina",
    price: 154.00,
    unit: "caja",
    stock: 400,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/utiles%20escolares/hojas%20bond/Papel%20Fotocopia%20A4%2080%20G%c2%a0Report.png",
    description: "Papel Fotocopia A4 80g Report. Caja con 5 paquetes de 500 hojas. Precio por paquete: S/ 15.40. Papel bond extrablanco de alta densidad, mayor rigidez y opacidad. Ideal para impresiones profesionales y documentos importantes.",
    deliveryDays: 1,
    brand: "Report",
    minOrder: 1,
    isRecurring: true,
    tags: ["Oficina", "Papel", "A4", "Impresión", "80g"],
    unitPrice: 15.40,
    unitPriceUnit: "pqte",
  },
  {
    id: "19",
    name: "Sobre con Burbuja A-02 Kraft Amarillo",
    sku: "TMO-EMP-001",
    category: "empaque",
    price: 50.00,
    unit: "pack",
    stock: 300,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/burbujas%20a2%20copia.png",
    description: "Sobre con Burbuja Air Pad A-02. Kraft Amarillo, medida 17×21 cm. Pack de 25 unidades. Protección acolchada ideal para envíos de documentos, accesorios y productos delicados. Cierre autoadhesivo.",
    deliveryDays: 1,
    brand: "Air Pad",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Sobre", "Burbuja", "Kraft", "Envío"],
  },
  {
    id: "20",
    name: "Sobre con Burbuja A-08 Kraft Amarillo",
    sku: "TMO-EMP-002",
    category: "empaque",
    price: 147.50,
    unit: "pack",
    stock: 200,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/burbujas%20a08%20copia.png",
    description: "Sobre con Burbuja Air Pad A-08. Kraft Amarillo, medida 32×44 cm. Pack de 25 unidades. Tamaño grande para envíos de libros, carpetas, tablets y productos medianos. Cierre autoadhesivo con excelente amortiguación.",
    deliveryDays: 1,
    brand: "Air Pad",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Sobre", "Burbuja", "Kraft", "Envío"],
  },
  {
    id: "21",
    name: "Papel Higiénico Family Pack Biodegradable",
    sku: "TMO-LIM-001",
    category: "limpieza",
    price: 124.00,
    unit: "pack",
    stock: 600,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/papel%20higienico/familiar/Papel%20higi%c3%a9nico%20Family%20pack,%20biodegradable.png",
    description: "Papel Higiénico Family Pack Biodegradable TMO. Doble hoja, 33 metros por rollo. Pack de 10 rollos. Suave, resistente y amigable con el medio ambiente. Ideal para hogares y oficinas.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Papel Higiénico", "Biodegradable", "Familiar"],
    unitPrice: 16.00,
    unitPriceUnit: "rollo",
  },
  {
    id: "22",
    name: "Papel Higiénico JUMBO Biodegradable 320m",
    sku: "TMO-LIM-002",
    category: "limpieza",
    price: 130.00,
    unit: "pqte",
    stock: 350,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/papel%20higienico/industrial/Papel%20higi%c3%a9nico%20jumbo%20biodegradable.png",
    description: "Papel Higiénico JUMBO Biodegradable TMO. Rollo de 320 metros, doble hoja. Paquete de 16 rollos. Alto rendimiento para uso industrial, comercial y oficinas con alto tráfico.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Papel Higiénico", "Biodegradable", "Industrial", "Jumbo"],
  },
  {
    id: "23",
    name: "Papel Higiénico Jumbo Biodegradable 250m",
    sku: "TMO-LIM-003",
    category: "limpieza",
    price: 72.00,
    unit: "caja",
    stock: 400,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/papel%20higienico/industrial/Papel%20higi%c3%a9nico%20JUMBO%20biodegradable%20550.png",
    description: "Papel Higiénico Jumbo Biodegradable TMO. Rollo de 250 metros, doble hoja. Caja de 6 rollos. Rendimiento óptimo para baños de mediano tráfico en oficinas, restaurantes y comercios.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Papel Higiénico", "Biodegradable", "Industrial", "Jumbo"],
  },
  {
    id: "24",
    name: "Papel Higiénico Institucional 500m",
    sku: "TMO-LIM-004",
    category: "limpieza",
    price: 79.00,
    unit: "pqte",
    stock: 280,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/papel%20higienico/industrial/papel%20higi%c3%a9nico%20Institucional%20500m.png",
    description: "Papel Higiénico Institucional Supremo. Rollo de 500 metros, color blanco, semi gofrado. Paquete de 6 rollos. Máximo rendimiento para baños de alto tráfico en industrias, centros comerciales e instituciones.",
    deliveryDays: 1,
    brand: "Supremo",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Papel Higiénico", "Industrial", "Institucional"],
  },
  {
    id: "25",
    name: "Sabanilla Fibra Sintética 60cm x 100m",
    sku: "TMO-SAB-001",
    category: "sabanillas",
    price: 351.00,
    unit: "caja",
    stock: 150,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/sabanillas/saban9lla%2060%20x100%20copia.jpg",
    description: "Sabanilla Fibra Sintética. Rollo de 60cm x 100m. Precortado cada 50cm (200 paños). Repelente a líquidos. Caja de 6 rollos. Ideal para clínicas, spa, estética y uso industrial.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Sabanillas", "Fibra Sintética", "Clínica", "Spa", "60cm"],
    unitPrice: 59.00,
    unitPriceUnit: "rollo",
  },
  {
    id: "26",
    name: "Sabanilla Fibra Sintética 50cm x 100m",
    sku: "TMO-SAB-002",
    category: "sabanillas",
    price: 297.00,
    unit: "caja",
    stock: 200,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/sabanillas/sabanilla%2050%20x100%20copia.png",
    description: "Sabanilla Fibra Sintética. Rollo de 50cm x 100m. Precortado cada 50cm (200 paños). Repelente a líquidos. Caja de 6 rollos. Ideal para clínicas, spa, estética y uso industrial.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Sabanillas", "Fibra Sintética", "Clínica", "Spa", "50cm"],
    unitPrice: 50.00,
    unitPriceUnit: "rollo",
  },
  {
    id: "27",
    name: "Jabón Líquido Hand Cleaning Lavanda",
    sku: "TMO-LIM-005",
    category: "limpieza",
    price: 36.00,
    unit: "galón",
    stock: 450,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/jabones/Jab%c3%b3n%20liquido%20Hand%20Cleaning%20Lavanda.png",
    description: "Jabón Líquido Hand Cleaning aroma Lavanda. Galón de 4 Litros. Fórmula antibacterial de alto rendimiento con aroma relajante. Ideal para dispensadores en oficinas, baños industriales y establecimientos comerciales.",
    deliveryDays: 1,
    brand: "Hand Cleaning",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Jabón", "Líquido", "Lavanda", "Antibacterial", "Galón"],
  },
  {
    id: "28",
    name: "Jabón Líquido Hand Cleaning Limón",
    sku: "TMO-LIM-006",
    category: "limpieza",
    price: 36.00,
    unit: "galón",
    stock: 400,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/jabones/Jab%c3%b3n%20liquido%20Hand%20Cleaning%20Limon.png",
    description: "Jabón Líquido Hand Cleaning aroma Limón. Galón de 4 Litros. Fórmula antibacterial con fragancia cítrica refrescante. Ideal para dispensadores en oficinas, baños industriales y establecimientos comerciales.",
    deliveryDays: 1,
    brand: "Hand Cleaning",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Jabón", "Líquido", "Limón", "Antibacterial", "Galón"],
  },
  {
    id: "29",
    name: "Jabón Líquido Hand Cleaning Frutos Rojos",
    sku: "TMO-LIM-007",
    category: "limpieza",
    price: 36.00,
    unit: "galón",
    stock: 380,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/jabones/Jab%c3%b3n%20liquido%20Hand%20Cleaning%20Fresa.png",
    description: "Jabón Líquido Hand Cleaning aroma Frutos Rojos. Galón de 4 Litros. Fórmula antibacterial con fragancia frutal agradable. Ideal para dispensadores en oficinas, baños industriales y establecimientos comerciales.",
    deliveryDays: 1,
    brand: "Hand Cleaning",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Jabón", "Líquido", "Frutos Rojos", "Antibacterial", "Galón"],
  },
  {
    id: "30",
    name: "Jabón Líquido Hand Cleaning Manzana Verde",
    sku: "TMO-LIM-008",
    category: "limpieza",
    price: 36.00,
    unit: "galón",
    stock: 420,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/jabones/Jab%c3%b3n%20liquido%20Hand%20Cleaning%20Manzana%20Verde.png",
    description: "Jabón Líquido Hand Cleaning aroma Manzana Verde. Galón de 4 Litros. Fórmula antibacterial con fragancia frutal fresca. Ideal para dispensadores en oficinas, baños industriales y establecimientos comerciales.",
    deliveryDays: 1,
    brand: "Hand Cleaning",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Jabón", "Líquido", "Manzana Verde", "Antibacterial", "Galón"],
  },
  {
    id: "31",
    name: "Dispensador de Papel MK-316",
    sku: "TMO-LIM-009",
    category: "limpieza",
    price: 40.00,
    unit: "unidad",
    stock: 120,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/dispensadores/Dispensador%20cuadrados.png",
    description: "Dispensador de Papel MK-316 marca TMO. Modelo manual. Dimensiones: 55.5 x 53.5 x 46.5 cm. Ideal para baños de oficinas, restaurantes e instalaciones industriales. Fácil instalación y recarga.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: false,
    tags: ["Limpieza", "Dispensador", "Papel", "Manual"],
  },
  {
    id: "32",
    name: "Dispensador de Papel MK-318 Blanco/Gris",
    sku: "TMO-LIM-010",
    category: "limpieza",
    price: 42.00,
    unit: "unidad",
    stock: 100,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/dispensadores/Dispensador%20con%20lado%20gris.png",
    description: "Dispensador de Papel MK-318 color Blanco/Gris. Modelo manual. Diseño compacto con panel lateral gris. Ideal para baños de oficinas, restaurantes e instalaciones industriales. Fácil instalación y recarga.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: false,
    tags: ["Limpieza", "Dispensador", "Papel", "Manual", "Blanco", "Gris"],
  },
  {
    id: "33",
    name: "Dispensador de Papel MK-616 Gris",
    sku: "TMO-LIM-011",
    category: "limpieza",
    price: 45.00,
    unit: "unidad",
    stock: 90,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/dispensadores/Dispensador%20gris.png",
    description: "Dispensador de Papel MK-616 color Gris. Modelo manual. Diseño robusto de alta capacidad. Ideal para baños de alto tráfico en industrias, centros comerciales e instituciones. Fácil instalación y recarga.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: false,
    tags: ["Limpieza", "Dispensador", "Papel", "Manual", "Gris"],
  },
  {
    id: "34",
    name: "Alcohol Gel en Sachet Delik2 1000ml",
    sku: "TMO-LIM-012",
    category: "limpieza",
    price: 15.00,
    unit: "unidad",
    stock: 500,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/limpieza/jabones/hand%20cleaning.png",
    description: "Alcohol Gel en Sachet Delik2. Presentación de 1000ml. Gel antibacterial de alta concentración, ideal para dispensadores automáticos y manuales. Formulación que hidrata las manos mientras desinfecta. Perfecto para oficinas, restaurantes, clínicas e industrias.",
    deliveryDays: 1,
    brand: "Delik2",
    minOrder: 1,
    isRecurring: true,
    tags: ["Limpieza", "Alcohol Gel", "Sachet", "Antibacterial", "Delik2", "1000ml"],
  },
  {
    id: "35",
    name: "Plástico Burbuja B-00 (13 x 16 cm)",
    sku: "TMO-EMP-003",
    category: "empaque",
    price: 37.50,
    unit: "pack",
    stock: 250,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/b00.png",
    description: "Plástico Burbuja B-00. Medida 13×16 cm. Ideal para proteger artículos pequeños y delicados durante el almacenamiento o envío. Excelente amortiguación contra golpes y vibraciones.",
    deliveryDays: 1,
    brand: "Genérico",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Plástico Burbuja", "Protección", "Envío", "B-00"],
  },
  {
    id: "36",
    name: "Plástico Burbuja B-05 (24 x 33 cm)",
    sku: "TMO-EMP-004",
    category: "empaque",
    price: 82.50,
    unit: "pack",
    stock: 180,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/a5.png",
    description: "Plástico Burbuja B-05. Medida 24×33 cm. Tamaño mediano ideal para proteger documentos, accesorios electrónicos y productos medianos. Liviano y flexible con excelente capacidad de amortiguación.",
    deliveryDays: 1,
    brand: "Genérico",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Plástico Burbuja", "Protección", "Envío", "B-05"],
  },
  {
    id: "37",
    name: "Plástico Burbuja B-09 (37 x 47 cm)",
    sku: "TMO-EMP-005",
    category: "empaque",
    price: 171.25,
    unit: "pack",
    stock: 120,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/b09.png",
    description: "Plástico Burbuja B-09. Medida 37×47 cm. Tamaño grande para proteger productos voluminosos, equipos electrónicos, vidrios y artículos frágiles. Máxima protección contra impactos durante el transporte y almacenamiento.",
    deliveryDays: 1,
    brand: "Genérico",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Plástico Burbuja", "Protección", "Envío", "B-09"],
  },
  {
    id: "38",
    name: "Sobre con Burbuja A-10 Kraft Amarillo",
    sku: "TMO-EMP-006",
    category: "empaque",
    price: 47.50,
    unit: "pack",
    stock: 220,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/empaque/burbujas/a10.png",
    description: "Sobre con Burbuja Air Pad A-10. Kraft Amarillo, medida 19.5×16.5 cm. Pack de 25 unidades. Protección acolchada compacta ideal para envíos de joyería, accesorios electrónicos pequeños y artículos delicados. Cierre autoadhesivo.",
    deliveryDays: 1,
    brand: "Air Pad",
    minOrder: 1,
    isRecurring: true,
    tags: ["Empaque", "Sobre", "Burbuja", "Kraft", "Envío", "A-10"],
  },
  {
    id: "39",
    name: "Sabanilla Doble Capa 50cm x 100m",
    sku: "TMO-SAB-003",
    category: "sabanillas",
    price: 351.00,
    unit: "caja",
    stock: 130,
    stockStatus: "in-stock",
    image: "http://imagenes.tmo.com.pe/imagenes/sabanillas/sabanilla%2050%20x%2050.png",
    description: "Sabanilla Doble Capa. Rollo de 50 cm x 100 m. Precortado en 200 paños de 50×50 cm. Una cara de papel y otra de plástico. Caja de 6 rollos. Ideal para clínicas, spa, estética y uso industrial.",
    deliveryDays: 1,
    brand: "TMO",
    minOrder: 1,
    isRecurring: true,
    tags: ["Sabanillas", "Doble Capa", "Clínica", "Spa", "50cm"],
    unitPrice: 59.00,
    unitPriceUnit: "rollo",
    isActive: true,
  },
];

export const searchSuggestions = [
  "Bolígrafo",
  "Faber-Castell",
  "Útiles de Oficina",
  "Papel Bond",
  "Papel A4",
  "Report",
  "Millennium",
  "Sobre Burbuja",
  "Empaque",
  "Air Pad",
  "Papel Higiénico",
  "Biodegradable",
  "Familiar",
  "Jumbo",
  "Institucional",
  "Sabanilla",
  "Fibra Sintética",
  "Doble Capa",
  "Jabón Líquido",
  "Hand Cleaning",
  "Lavanda",
  "Limón",
  "Frutos Rojos",
  "Manzana Verde",
  "Dispensador",
  "MK-316",
  "MK-318",
  "MK-616",
  "Alcohol Gel",
  "Delik2",
  "Sachet",
  "Plástico Burbuja",
  "B-00",
  "B-05",
  "B-09",
  "A-10",
];

export function formatPrice(price: number): string {
  return "S/ " + new Intl.NumberFormat("es-PE", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  }).format(price);
}